In [22]:
import numpy as np
import pandas as pd
import datetime

In [23]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [24]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [25]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [26]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [27]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [28]:
date['date']=pd.to_datetime(date['date'])

In [29]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB



1.   dt.year             → Year
2. .dt.month            → Month number
3. .dt.month_name()     → Month name
4. .dt.day              → Date/Day number
5. .dt.dayofweek        → Weekday number
6. .dt.day_name()       → Weekday name
7. .dt.isocalendar().week → Week number

In [30]:
date['date_year']=date['date'].dt.year
date['date_month']=date['date'].dt.month
date['date_month_name']=date['date'].dt.month_name()
date['date_day']=date['date'].dt.day
date['date_dayofweek']=date['date'].dt.dayofweek
date['date_dow_name']=date['date'].dt.day_name()
date['date_month']=date['date'].dt.month
date['date_week']=date['date'].dt.isocalendar().week
date['quarter']=date['date'].dt.quarter

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dayofweek,date_dow_name,date_week,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [31]:
#is weekend or not

date['date_is_weekend']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date['semester']=np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dayofweek,date_dow_name,date_week,quarter,date_is_weekend,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,50,4,0,2
1,2018-08-15,2018,8,August,15,2,Wednesday,33,3,0,2
2,2018-10-23,2018,10,October,23,1,Tuesday,43,4,0,2
3,2019-08-17,2019,8,August,17,5,Saturday,33,3,1,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

In [33]:
today=datetime.datetime.today()
today

datetime.datetime(2026, 10, 5, 14, 21, 46, 283387)

In [36]:
today-date['date']

0     2491 days 14:21:46.283387
1     2973 days 14:21:46.283387
2     2904 days 14:21:46.283387
3     2606 days 14:21:46.283387
4     2829 days 14:21:46.283387
                 ...
995   2919 days 14:21:46.283387
996   2860 days 14:21:46.283387
997   2708 days 14:21:46.283387
998   2773 days 14:21:46.283387
999   2547 days 14:21:46.283387
Name: date, Length: 1000, dtype: timedelta64[ns]

In [37]:
(today-date['date']).dt.days

0      2491
1      2973
2      2904
3      2606
4      2829
       ...
995    2919
996    2860
997    2708
998    2773
999    2547
Name: date, Length: 1000, dtype: int64

In [44]:

    (today.dt.year - date['date'].dt.year) * 12
    + (today.dt.month - date['date'].dt.month)

AttributeError: 'datetime.datetime' object has no attribute 'dt'

In [45]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [46]:
time['date']=pd.to_datetime(time['date'])

In [47]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [49]:
time['date'] = pd.to_datetime(time['date'])
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [50]:
today - time['date']

0     4677 days 13:31:46.283387
1     4541 days 14:41:46.283387
2     5027 days 14:00:46.283387
3     4329 days 13:50:46.283387
4     4726 days 15:10:46.283387
                 ...
995   5316 days 13:31:46.283387
996   4637 days 15:07:46.283387
997   5102 days 14:44:46.283387
998   5218 days 14:47:46.283387
999   4490 days 14:56:46.283387
Name: date, Length: 1000, dtype: timedelta64[ns]

In [52]:
(today - time['date'])/np.timedelta64(1,'s')

0      4.041415e+08
1      3.923953e+08
2      4.343832e+08
3      3.740754e+08
4      4.083810e+08
           ...
995    4.593511e+08
996    4.006913e+08
997    4.408659e+08
998    4.508885e+08
999    3.879898e+08
Name: date, Length: 1000, dtype: float64

In [53]:
(today - time['date'])/np.timedelta64(1,'m')

0      6.735692e+06
1      6.539922e+06
2      7.239721e+06
3      6.234591e+06
4      6.806351e+06
           ...
995    7.655852e+06
996    6.678188e+06
997    7.347765e+06
998    7.514808e+06
999    6.466497e+06
Name: date, Length: 1000, dtype: float64

In [54]:
(today - time['date'])/np.timedelta64(1,'h')

0      112261.529523
1      108998.696190
2      120662.012856
3      103909.846190
4      113439.179523
           ...
995    127597.529523
996    111303.129523
997    122462.746190
998    125246.796190
999    107774.946190
Name: date, Length: 1000, dtype: float64